# Generated by Django 6.1.1 on 2026-10-06 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from sync.db import insert_only, sequenced_table


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('sync', '0001_server_seq_functions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.UUIDField()),
                ('entity', models.CharField(max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('op_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=8)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('merged', 'Merged'), ('rejected', 'Rejected')], max_length=8)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('result', models.JSONField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'op_id'), name='applied_op_user_op_id_unique'), models.CheckConstraint(condition=models.Q(('status', 'rejected'), ('reason', ''), _connector='OR'), name='applied_op_reason_only_when_rejected')],
            },
        ),
        migrations.CreateModel(
            name='EntityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('changed', 'Changed'), ('overwritten', 'Overwritten'), ('deleted', 'Deleted'), ('restored', 'Restored')], max_length=16)),
                ('field', models.CharField(blank=True, max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('op_id', models.UUIDField(blank=True, null=True)),
                ('server_seq', models.BigIntegerField(editable=False, unique=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.group')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entity history',
                'indexes': [models.Index(fields=['owner', 'server_seq'], name='history_owner_seq'), models.Index(fields=['group', 'server_seq'], name='history_group_seq'), models.Index(fields=['entity', 'entity_id'], name='history_entity')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('owner__isnull', False)), models.Q(('group__isnull', False), ('owner__isnull', True)), _connector='OR'), name='history_one_scope')],
            },
        ),
        sequenced_table("sync_entityhistory"),
        insert_only("sync_entityhistory"),
        insert_only("sync_appliedop"),
    ]
