# Generated by Django 6.1.1 on 2026-10-06 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('sync', '0002_applied_ops_and_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entityhistory',
            name='history_entity',
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityhistory',
            name='kind',
            field=models.CharField(choices=[('created', 'Created'), ('changed', 'Changed'), ('overwritten', 'Overwritten'), ('deleted', 'Deleted'), ('restored', 'Restored'), ('discarded', 'Discarded')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='entityhistory',
            index=models.Index(fields=['entity', 'entity_id', 'version'], name='history_entity_version'),
        ),
    ]
