# Generated by Django 6.1.1 on 2026-10-06 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from sync.db import insert_only, synced_table


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sync', '0001_server_seq_functions'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('server_seq', models.BigIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=7)),
                ('total_limit_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'server_seq'], name='budget_owner_seq')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'entity_id'), name='budget_owner_entity_id_unique'), models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='budget_currency_code'), models.CheckConstraint(condition=models.Q(('month__regex', '^[0-9]{4}-(0[1-9]|1[0-2])$')), name='budget_month_format'), models.CheckConstraint(condition=models.Q(('total_limit_minor__isnull', True), ('total_limit_minor__gt', 0), _connector='OR'), name='budget_limit_positive')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('server_seq', models.BigIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('icon', models.CharField(max_length=40)),
                ('monthly_limit_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('archived', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'indexes': [models.Index(fields=['owner', 'server_seq'], name='category_owner_seq')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'entity_id'), name='category_owner_entity_id_unique'), models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='category_currency_code'), models.CheckConstraint(condition=models.Q(('monthly_limit_minor__isnull', True), ('monthly_limit_minor__gt', 0), _connector='OR'), name='category_limit_positive')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('server_seq', models.BigIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('category_id', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('voice', 'Voice'), ('receipt', 'Receipt')], default='manual', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'server_seq'], name='expense_owner_seq')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'entity_id'), name='expense_owner_entity_id_unique'), models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='expense_currency_code'), models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='expense_amount_positive'), models.CheckConstraint(condition=models.Q(('source__in', ['manual', 'voice', 'receipt'])), name='expense_source_valid')],
            },
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('server_seq', models.BigIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('schedule_type', models.CharField(choices=[('monthly', 'Monthly'), ('oneOff', 'One Off'), ('irregular', 'Irregular')], max_length=16)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'server_seq'], name='income_owner_seq')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'entity_id'), name='income_owner_entity_id_unique'), models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='income_currency_code'), models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='income_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('date__isnull', True), ('day_of_month__gte', 1), ('day_of_month__isnull', False), ('day_of_month__lte', 31), ('schedule_type', 'monthly')), models.Q(('date__isnull', False), ('day_of_month__isnull', True), ('schedule_type', 'oneOff')), models.Q(('date__isnull', True), ('day_of_month__isnull', True), ('schedule_type', 'irregular')), _connector='OR'), name='income_schedule_valid')],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('server_seq', models.BigIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='groups.member')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups.group')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.settlement')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='groups.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'server_seq'], name='settlement_group_seq')],
                'constraints': [models.UniqueConstraint(fields=('entity_id',), name='settlement_entity_id_unique'), models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='settlement_amount_positive'), models.CheckConstraint(condition=models.Q(('from_member', models.F('to_member')), _negated=True), name='settlement_not_to_self'), models.CheckConstraint(condition=models.Q(('deleted', False)), name='settlement_never_deleted'), models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='settlement_currency_code')],
            },
        ),
        migrations.CreateModel(
            name='SharedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('server_seq', models.BigIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('split', models.JSONField()),
                ('shares', models.JSONField()),
                ('category_id', models.CharField(blank=True, max_length=64, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='groups.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'server_seq'], name='shared_expense_group_seq')],
                'constraints': [models.UniqueConstraint(fields=('entity_id',), name='shared_expense_entity_id_unique'), models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='shared_expense_amount_positive'), models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='shared_expense_currency_code')],
            },
        ),
        synced_table("ledger_expense"),
        synced_table("ledger_category"),
        synced_table("ledger_incomesource"),
        synced_table("ledger_budget"),
        synced_table("ledger_sharedexpense"),
        synced_table("ledger_settlement"),
        insert_only("ledger_settlement"),
    ]
