// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    expenses,
    categories,
    incomeSources,
    budgets,
    budgetCategoryLimits,
    outbox,
    syncState,
    entityHistory,
    expensesDate,
    outboxStatusSeq,
    entityHistoryEntity,
  ];
  late final Shape0 expenses = Shape0(
    source: i0.VersionedTable(
      entityName: 'expenses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_12,
        _column_13,
        _column_6,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 incomeSources = Shape2(
    source: i0.VersionedTable(
      entityName: 'income_sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 budgets = Shape3(
    source: i0.VersionedTable(
      entityName: 'budgets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_18,
        _column_19,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 budgetCategoryLimits = Shape4(
    source: i0.VersionedTable(
      entityName: 'budget_category_limits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_20,
        _column_7,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 outbox = Shape5(
    source: i0.VersionedTable(
      entityName: 'outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 syncState = Shape6(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_33, _column_34, _column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 entityHistory = Shape7(
    source: i0.VersionedTable(
      entityName: 'entity_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_24,
        _column_25,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_3,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index expensesDate = i1.Index(
    'expenses_date',
    'CREATE INDEX expenses_date ON expenses (date)',
  );
  final i1.Index outboxStatusSeq = i1.Index(
    'outbox_status_seq',
    'CREATE INDEX outbox_status_seq ON outbox (status, seq)',
  );
  final i1.Index entityHistoryEntity = i1.Index(
    'entity_history_entity',
    'CREATE INDEX entity_history_entity ON entity_history (entity, entity_id)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedBy =>
      columnsByName['updated_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverSeq =>
      columnsByName['server_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get amountMinor =>
      columnsByName['amount_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoryId =>
      columnsByName['category_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_by',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'server_seq',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'amount_minor',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'currency',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedBy =>
      columnsByName['updated_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverSeq =>
      columnsByName['server_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get monthlyLimitMinor =>
      columnsByName['monthly_limit_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get archived =>
      columnsByName['archived']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'monthly_limit_minor',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (archived IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedBy =>
      columnsByName['updated_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverSeq =>
      columnsByName['server_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get amountMinor =>
      columnsByName['amount_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scheduleType =>
      columnsByName['schedule_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get dayOfMonth =>
      columnsByName['day_of_month']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'schedule_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'day_of_month',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedBy =>
      columnsByName['updated_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverSeq =>
      columnsByName['server_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get month =>
      columnsByName['month']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalLimitMinor =>
      columnsByName['total_limit_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'month',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_limit_minor',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedBy =>
      columnsByName['updated_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverSeq =>
      columnsByName['server_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get budgetId =>
      columnsByName['budget_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoryId =>
      columnsByName['category_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get limitMinor =>
      columnsByName['limit_minor']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'budget_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'limit_minor',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get seq =>
      columnsByName['seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get opId =>
      columnsByName['op_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entity =>
      columnsByName['entity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get opType =>
      columnsByName['op_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get changedFields =>
      columnsByName['changed_fields']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get baseVersion =>
      columnsByName['base_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rejectReason =>
      columnsByName['reject_reason']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'seq',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'op_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'op_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'changed_fields',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'base_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempts',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'pending\'',
      defaultValue: const i1.CustomExpression('\'pending\''),
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reject_reason',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cursor =>
      columnsByName['cursor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastSyncAt =>
      columnsByName['last_sync_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cursor',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_sync_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'account_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entity =>
      columnsByName['entity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get field =>
      columnsByName['field']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get oldValue =>
      columnsByName['old_value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get newValue =>
      columnsByName['new_value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get changedBy =>
      columnsByName['changed_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverSeq =>
      columnsByName['server_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get changedAt =>
      columnsByName['changed_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'changed\'',
      defaultValue: const i1.CustomExpression('\'changed\''),
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'field',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'old_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'new_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'changed_by',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'changed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    expenses,
    categories,
    incomeSources,
    budgets,
    budgetCategoryLimits,
    outbox,
    syncState,
    entityHistory,
    serverRows,
    expensesDate,
    outboxStatusSeq,
    entityHistoryEntity,
  ];
  late final Shape0 expenses = Shape0(
    source: i0.VersionedTable(
      entityName: 'expenses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_12,
        _column_13,
        _column_6,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 incomeSources = Shape2(
    source: i0.VersionedTable(
      entityName: 'income_sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 budgets = Shape3(
    source: i0.VersionedTable(
      entityName: 'budgets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_18,
        _column_19,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 budgetCategoryLimits = Shape4(
    source: i0.VersionedTable(
      entityName: 'budget_category_limits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_20,
        _column_7,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 outbox = Shape5(
    source: i0.VersionedTable(
      entityName: 'outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 syncState = Shape6(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_33, _column_34, _column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 entityHistory = Shape7(
    source: i0.VersionedTable(
      entityName: 'entity_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_24,
        _column_25,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_3,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 serverRows = Shape8(
    source: i0.VersionedTable(
      entityName: 'server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(entity, entity_id)'],
      columns: [_column_24, _column_25, _column_43, _column_44],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index expensesDate = i1.Index(
    'expenses_date',
    'CREATE INDEX expenses_date ON expenses (date)',
  );
  final i1.Index outboxStatusSeq = i1.Index(
    'outbox_status_seq',
    'CREATE INDEX outbox_status_seq ON outbox (status, seq)',
  );
  final i1.Index entityHistoryEntity = i1.Index(
    'entity_history_entity',
    'CREATE INDEX entity_history_entity ON entity_history (entity, entity_id)',
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get entity =>
      columnsByName['entity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverSeq =>
      columnsByName['server_seq']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'server_seq',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    expenses,
    categories,
    incomeSources,
    budgets,
    budgetCategoryLimits,
    outbox,
    syncState,
    entityHistory,
    serverRows,
    groups,
    members,
    groupBackfills,
    expensesDate,
    outboxStatusSeq,
    entityHistoryEntity,
    membersGroup,
  ];
  late final Shape0 expenses = Shape0(
    source: i0.VersionedTable(
      entityName: 'expenses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_12,
        _column_13,
        _column_6,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 incomeSources = Shape2(
    source: i0.VersionedTable(
      entityName: 'income_sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 budgets = Shape3(
    source: i0.VersionedTable(
      entityName: 'budgets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_18,
        _column_19,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 budgetCategoryLimits = Shape4(
    source: i0.VersionedTable(
      entityName: 'budget_category_limits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_20,
        _column_7,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 outbox = Shape5(
    source: i0.VersionedTable(
      entityName: 'outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 syncState = Shape6(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_33, _column_34, _column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 entityHistory = Shape7(
    source: i0.VersionedTable(
      entityName: 'entity_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_24,
        _column_25,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_3,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 serverRows = Shape8(
    source: i0.VersionedTable(
      entityName: 'server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(entity, entity_id)'],
      columns: [_column_24, _column_25, _column_43, _column_44],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 groups = Shape9(
    source: i0.VersionedTable(
      entityName: 'groups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 members = Shape10(
    source: i0.VersionedTable(
      entityName: 'members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 groupBackfills = Shape11(
    source: i0.VersionedTable(
      entityName: 'group_backfills',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(group_id)'],
      columns: [_column_45, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index expensesDate = i1.Index(
    'expenses_date',
    'CREATE INDEX expenses_date ON expenses (date)',
  );
  final i1.Index outboxStatusSeq = i1.Index(
    'outbox_status_seq',
    'CREATE INDEX outbox_status_seq ON outbox (status, seq)',
  );
  final i1.Index entityHistoryEntity = i1.Index(
    'entity_history_entity',
    'CREATE INDEX entity_history_entity ON entity_history (entity, entity_id)',
  );
  final i1.Index membersGroup = i1.Index(
    'members_group',
    'CREATE INDEX members_group ON members (group_id)',
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedBy =>
      columnsByName['updated_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverSeq =>
      columnsByName['server_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedBy =>
      columnsByName['updated_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverSeq =>
      columnsByName['server_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get cursor =>
      columnsByName['cursor']! as i1.GeneratedColumn<int>;
}

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    expenses,
    categories,
    incomeSources,
    budgets,
    budgetCategoryLimits,
    outbox,
    syncState,
    entityHistory,
    serverRows,
    groups,
    members,
    groupBackfills,
    sharedExpenses,
    expensesDate,
    outboxStatusSeq,
    entityHistoryEntity,
    membersGroup,
    sharedExpensesGroup,
  ];
  late final Shape0 expenses = Shape0(
    source: i0.VersionedTable(
      entityName: 'expenses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_12,
        _column_13,
        _column_6,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 incomeSources = Shape2(
    source: i0.VersionedTable(
      entityName: 'income_sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 budgets = Shape3(
    source: i0.VersionedTable(
      entityName: 'budgets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_18,
        _column_19,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 budgetCategoryLimits = Shape4(
    source: i0.VersionedTable(
      entityName: 'budget_category_limits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_20,
        _column_7,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 outbox = Shape5(
    source: i0.VersionedTable(
      entityName: 'outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 syncState = Shape6(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_33, _column_34, _column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 entityHistory = Shape7(
    source: i0.VersionedTable(
      entityName: 'entity_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_24,
        _column_25,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_3,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 serverRows = Shape8(
    source: i0.VersionedTable(
      entityName: 'server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(entity, entity_id)'],
      columns: [_column_24, _column_25, _column_43, _column_44],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 groups = Shape9(
    source: i0.VersionedTable(
      entityName: 'groups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 members = Shape10(
    source: i0.VersionedTable(
      entityName: 'members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 groupBackfills = Shape11(
    source: i0.VersionedTable(
      entityName: 'group_backfills',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(group_id)'],
      columns: [_column_45, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 sharedExpenses = Shape12(
    source: i0.VersionedTable(
      entityName: 'shared_expenses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_45,
        _column_48,
        _column_5,
        _column_6,
        _column_8,
        _column_49,
        _column_50,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index expensesDate = i1.Index(
    'expenses_date',
    'CREATE INDEX expenses_date ON expenses (date)',
  );
  final i1.Index outboxStatusSeq = i1.Index(
    'outbox_status_seq',
    'CREATE INDEX outbox_status_seq ON outbox (status, seq)',
  );
  final i1.Index entityHistoryEntity = i1.Index(
    'entity_history_entity',
    'CREATE INDEX entity_history_entity ON entity_history (entity, entity_id)',
  );
  final i1.Index membersGroup = i1.Index(
    'members_group',
    'CREATE INDEX members_group ON members (group_id)',
  );
  final i1.Index sharedExpensesGroup = i1.Index(
    'shared_expenses_group',
    'CREATE INDEX shared_expenses_group ON shared_expenses (group_id)',
  );
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedBy =>
      columnsByName['updated_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverSeq =>
      columnsByName['server_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payerId =>
      columnsByName['payer_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get amountMinor =>
      columnsByName['amount_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get split =>
      columnsByName['split']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get shares =>
      columnsByName['shares']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoryId =>
      columnsByName['category_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payer_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'split',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'shares',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    expenses,
    categories,
    incomeSources,
    budgets,
    budgetCategoryLimits,
    outbox,
    syncState,
    entityHistory,
    serverRows,
    groups,
    members,
    groupBackfills,
    sharedExpenses,
    settlements,
    expensesDate,
    outboxStatusSeq,
    entityHistoryEntity,
    membersGroup,
    sharedExpensesGroup,
    settlementsGroup,
  ];
  late final Shape0 expenses = Shape0(
    source: i0.VersionedTable(
      entityName: 'expenses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_12,
        _column_13,
        _column_6,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 incomeSources = Shape2(
    source: i0.VersionedTable(
      entityName: 'income_sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 budgets = Shape3(
    source: i0.VersionedTable(
      entityName: 'budgets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_18,
        _column_19,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 budgetCategoryLimits = Shape4(
    source: i0.VersionedTable(
      entityName: 'budget_category_limits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_20,
        _column_7,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 outbox = Shape5(
    source: i0.VersionedTable(
      entityName: 'outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 syncState = Shape6(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_33, _column_34, _column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 entityHistory = Shape7(
    source: i0.VersionedTable(
      entityName: 'entity_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_24,
        _column_25,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_3,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 serverRows = Shape8(
    source: i0.VersionedTable(
      entityName: 'server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(entity, entity_id)'],
      columns: [_column_24, _column_25, _column_43, _column_44],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 groups = Shape9(
    source: i0.VersionedTable(
      entityName: 'groups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 members = Shape10(
    source: i0.VersionedTable(
      entityName: 'members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 groupBackfills = Shape11(
    source: i0.VersionedTable(
      entityName: 'group_backfills',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(group_id)'],
      columns: [_column_45, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 sharedExpenses = Shape12(
    source: i0.VersionedTable(
      entityName: 'shared_expenses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_45,
        _column_48,
        _column_5,
        _column_6,
        _column_8,
        _column_49,
        _column_50,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 settlements = Shape13(
    source: i0.VersionedTable(
      entityName: 'settlements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_45,
        _column_52,
        _column_53,
        _column_5,
        _column_6,
        _column_8,
        _column_54,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index expensesDate = i1.Index(
    'expenses_date',
    'CREATE INDEX expenses_date ON expenses (date)',
  );
  final i1.Index outboxStatusSeq = i1.Index(
    'outbox_status_seq',
    'CREATE INDEX outbox_status_seq ON outbox (status, seq)',
  );
  final i1.Index entityHistoryEntity = i1.Index(
    'entity_history_entity',
    'CREATE INDEX entity_history_entity ON entity_history (entity, entity_id)',
  );
  final i1.Index membersGroup = i1.Index(
    'members_group',
    'CREATE INDEX members_group ON members (group_id)',
  );
  final i1.Index sharedExpensesGroup = i1.Index(
    'shared_expenses_group',
    'CREATE INDEX shared_expenses_group ON shared_expenses (group_id)',
  );
  final i1.Index settlementsGroup = i1.Index(
    'settlements_group',
    'CREATE INDEX settlements_group ON settlements (group_id)',
  );
}

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedBy =>
      columnsByName['updated_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverSeq =>
      columnsByName['server_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fromMemberId =>
      columnsByName['from_member_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get toMemberId =>
      columnsByName['to_member_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get amountMinor =>
      columnsByName['amount_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reversesId =>
      columnsByName['reverses_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'from_member_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'to_member_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reverses_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    expenses,
    categories,
    incomeSources,
    budgets,
    budgetCategoryLimits,
    outbox,
    syncState,
    entityHistory,
    serverRows,
    groups,
    members,
    groupBackfills,
    sharedExpenses,
    settlements,
    sentAlerts,
    expensesDate,
    outboxStatusSeq,
    entityHistoryEntity,
    membersGroup,
    sharedExpensesGroup,
    settlementsGroup,
  ];
  late final Shape0 expenses = Shape0(
    source: i0.VersionedTable(
      entityName: 'expenses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_12,
        _column_13,
        _column_6,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 incomeSources = Shape2(
    source: i0.VersionedTable(
      entityName: 'income_sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_5,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 budgets = Shape3(
    source: i0.VersionedTable(
      entityName: 'budgets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_18,
        _column_19,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 budgetCategoryLimits = Shape4(
    source: i0.VersionedTable(
      entityName: 'budget_category_limits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_20,
        _column_7,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 outbox = Shape5(
    source: i0.VersionedTable(
      entityName: 'outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 syncState = Shape6(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_33, _column_34, _column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 entityHistory = Shape7(
    source: i0.VersionedTable(
      entityName: 'entity_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_24,
        _column_25,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_3,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 serverRows = Shape8(
    source: i0.VersionedTable(
      entityName: 'server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(entity, entity_id)'],
      columns: [_column_24, _column_25, _column_43, _column_44],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 groups = Shape9(
    source: i0.VersionedTable(
      entityName: 'groups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_11,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 members = Shape10(
    source: i0.VersionedTable(
      entityName: 'members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 groupBackfills = Shape11(
    source: i0.VersionedTable(
      entityName: 'group_backfills',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(group_id)'],
      columns: [_column_45, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 sharedExpenses = Shape12(
    source: i0.VersionedTable(
      entityName: 'shared_expenses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_45,
        _column_48,
        _column_5,
        _column_6,
        _column_8,
        _column_49,
        _column_50,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 settlements = Shape13(
    source: i0.VersionedTable(
      entityName: 'settlements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_45,
        _column_52,
        _column_53,
        _column_5,
        _column_6,
        _column_8,
        _column_54,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 sentAlerts = Shape14(
    source: i0.VersionedTable(
      entityName: 'sent_alerts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_55, _column_56, _column_57, _column_58, _column_59],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index expensesDate = i1.Index(
    'expenses_date',
    'CREATE INDEX expenses_date ON expenses (date)',
  );
  final i1.Index outboxStatusSeq = i1.Index(
    'outbox_status_seq',
    'CREATE INDEX outbox_status_seq ON outbox (status, seq)',
  );
  final i1.Index entityHistoryEntity = i1.Index(
    'entity_history_entity',
    'CREATE INDEX entity_history_entity ON entity_history (entity, entity_id)',
  );
  final i1.Index membersGroup = i1.Index(
    'members_group',
    'CREATE INDEX members_group ON members (group_id)',
  );
  final i1.Index sharedExpensesGroup = i1.Index(
    'shared_expenses_group',
    'CREATE INDEX shared_expenses_group ON shared_expenses (group_id)',
  );
  final i1.Index settlementsGroup = i1.Index(
    'settlements_group',
    'CREATE INDEX settlements_group ON settlements (group_id)',
  );
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get situation =>
      columnsByName['situation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sentOn =>
      columnsByName['sent_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get runOut =>
      columnsByName['run_out']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'situation',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sent_on',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'run_out',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
  ),
);
