# Generated by Django 6.1.1 on 2026-10-06 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from sync.db import synced_table


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sync', '0001_server_seq_functions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('server_seq', models.BigIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('currency', models.CharField(max_length=3)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('server_seq', models.BigIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('entity_id',), name='group_entity_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='group_currency_code'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['group', 'server_seq'], name='member_group_seq'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('entity_id',), name='member_entity_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('user__isnull', False)), fields=('group', 'user'), name='member_one_active_per_user'),
        ),
        synced_table("groups_group"),
        synced_table("groups_member"),
    ]
